# ==============================================================================
# TERRAFORM INPUT VARIABLES
# These values are injected at runtime by the GitHub Actions pipeline via the
# -var flag on terraform apply/destroy. They are never hardcoded in source.
#
# Flow:
#   GitHub Actions step output (steps.build.outputs.target_image_tag)
#       → -var="image_tag=..."
#           → EC2 user_data script
#               → docker run "${var.image_tag}"
# ==============================================================================

# ------------------------------------------------------------------------------
# image_tag
# The fully-qualified container image reference pushed to GHCR in the build
# step. Format: ghcr.io/<owner>/<repo>/user-api:<git-sha>
# Example: ghcr.io/aadieng100/devsecops_project01/user-api:83b947df...
# ------------------------------------------------------------------------------
variable "image_tag" {
  type        = string
  description = "The target container image tag inside GHCR"
}

# ------------------------------------------------------------------------------
# github_token
# The short-lived GITHUB_TOKEN generated by GitHub Actions for the current run.
# Used exclusively inside the EC2 user_data script to authenticate to GHCR
# and pull the private container image. Marked sensitive = true so Terraform
# never prints this value in plan/apply output or state file diffs.
# ------------------------------------------------------------------------------
variable "github_token" {
  type        = string
  description = "Short-lived automation token to pull the private image"
  sensitive   = true
}

# ------------------------------------------------------------------------------
# github_actor
# The GitHub username of the user or bot that triggered the workflow run.
# Used as the --username argument in `docker login ghcr.io` inside user_data.
# Example: "aadieng100"
# ------------------------------------------------------------------------------
variable "github_actor" {
  type        = string
  description = "The GitHub username triggering the execution"
}